//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DumpUploader.AzureChannel {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.danhu.com", ConfigurationName="AzureChannel.ChannelServer")]
    public interface ChannelServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.danhu.com/ChannelServer/Echo", ReplyAction="http://www.danhu.com/ChannelServer/EchoResponse")]
        DumpUploader.AzureChannel.EchoResponse Echo(DumpUploader.AzureChannel.EchoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.danhu.com/ChannelServer/Upload")]
        void Upload(DumpUploader.AzureChannel.UploadEvent request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Echo", WrapperNamespace="http://www.danhu.com", IsWrapped=true)]
    public partial class EchoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.danhu.com", Order=0)]
        public string msg;
        
        public EchoRequest() {
        }
        
        public EchoRequest(string msg) {
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EchoResponse", WrapperNamespace="http://www.danhu.com", IsWrapped=true)]
    public partial class EchoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.danhu.com", Order=0)]
        public string EchoResult;
        
        public EchoResponse() {
        }
        
        public EchoResponse(string EchoResult) {
            this.EchoResult = EchoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadEvent", WrapperNamespace="http://www.danhu.com", IsWrapped=true)]
    public partial class UploadEvent {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.danhu.com")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.danhu.com")]
        public int Type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.danhu.com", Order=0)]
        public System.IO.Stream FileData;
        
        public UploadEvent() {
        }
        
        public UploadEvent(string FileName, int Type, System.IO.Stream FileData) {
            this.FileName = FileName;
            this.Type = Type;
            this.FileData = FileData;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChannelServerChannel : DumpUploader.AzureChannel.ChannelServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChannelServerClient : System.ServiceModel.ClientBase<DumpUploader.AzureChannel.ChannelServer>, DumpUploader.AzureChannel.ChannelServer {
        
        public ChannelServerClient() {
        }
        
        public ChannelServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChannelServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChannelServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChannelServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DumpUploader.AzureChannel.EchoResponse Echo(DumpUploader.AzureChannel.EchoRequest request) {
            return base.Channel.Echo(request);
        }
        
        public void Upload(DumpUploader.AzureChannel.UploadEvent request) {
            base.Channel.Upload(request);
        }
    }
}
